ignore:
  - "panoptes/pocs/camera/gphoto/canon.py"
  - "panoptes/pocs/camera/sbig.py"
  - "panoptes/pocs/camera/sbigudrv.py"
  - "panoptes/pocs/camera/fli.py"
  - "panoptes/pocs/camera/libfli.py"
  - "panoptes/pocs/camera/libfliconstants.py"
  - "panoptes/pocs/camera/zwo.py"
  - "panoptes/pocs/camera/libasi.py"
  - "panoptes/pocs/tests/bisque/*"
  - "panoptes/pocs/dome/bisque.py"
  - "panoptes/pocs/mount/bisque.py"
  - "panoptes/pocs/mount/serial.py"
  - "panoptes/pocs/mount/ioptron.py"
  - "panoptes/pocs/focuser/birger.py"
  - "panoptes/pocs/focuser/focuslynx.py"
  - "panoptes/pocs/filterwheel/libefw.py"
  - "panoptes/pocs/filterwheel/sbig.py"
  - "panoptes/pocs/filterwheel/zwo.py"
