ignore:
  - "pocs/camera/canon.py"
  - "pocs/camera/sbig.py"
  - "pocs/camera/sbigudrv.py"
  - "pocs/camera/fli.py"
  - "pocs/camera/libfli.py"
  - "pocs/camera/libfliconstants.py"
  - "pocs/camera/zwo.py"
  - "pocs/camera/libasi.py"
  - "pocs/tests/bisque/*"
  - "pocs/dome/bisque.py"
  - "pocs/mount/bisque.py"
  - "pocs/mount/serial.py"
  - "pocs/mount/ioptron.py"
  - "pocs/focuser/birger.py"
  - "pocs/focuser/focuslynx.py"
  - "pocs/filterwheel/libefw.py"
  - "pocs/filterwheel/sbig.py"
  - "pocs/filterwheel/zwo.py"
