ignore:
  - "pocs/utils/data.py"
  - "pocs/utils/google/*"
  - "pocs/camera/canon_gphoto2.py"
  - "pocs/camera/sbig.py"
  - "pocs/camera/sbigudrv.py"
  - "pocs/tests/*"
  - "pocs/tests/bisque/*"
  - "pocs/dome/bisque.py"
  - "pocs/mount/bisque.py"
  - "pocs/mount/serial.py"
  - "pocs/mount/ioptron.py"
  - "pocs/focuser/birger.py"
