ignore:
  - "pocs/utils/data.py"
  - "pocs/utils/google/*"
  - "pocs/utils/jupyter/*"
  - "pocs/utils/rs232.py"
  - "pocs/camera/canon_gphoto2.py"
  - "pocs/camera/sbig.py"
  - "pocs/camera/sbigudrv.py"
  - "pocs/tests/test_sbig.py"
  - "pocs/mount/mount_serial.py"
  - "pocs/mount/ioptron.py"
