steps:
# Build
# AMD Build
- name: 'gcr.io/cloud-builders/docker'
  id: 'amd64'
  args:
  - 'build'
  - '-f=docker/Dockerfile'
  - '--build-arg=arch=amd64'
  - '--tag=gcr.io/${PROJECT_ID}/pocs:amd64'
  - '.'
  waitFor: ['-']

# Push
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-amd64'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/pocs:amd64'
  waitFor: ['amd64']

# Manifest file for multiarch
- name: 'gcr.io/cloud-builders/docker'
  id: 'manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'create'
  - 'gcr.io/${PROJECT_ID}/pocs:latest'
  - 'gcr.io/${PROJECT_ID}/pocs:amd64'
  waitFor: ['push-amd64']

# Push manifest file
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'push'
  - 'gcr.io/${PROJECT_ID}/pocs:latest'
  waitFor: ['manifest']
images:
  - 'gcr.io/${PROJECT_ID}/pocs:amd64'
