version: '3.7'
services:
  develop-env:
    image: "${IMAGE:-panoptes-pocs}:${TAG:-developer-env}"
    init: true
    container_name: "${CONTAINER_NAME:-pocs-developer-env}"
    privileged: true
    network_mode: host
    env_file: $PANDIR/env
    volumes:
      - pandir:/var/panoptes
volumes:
  pandir:
    driver: local
    driver_opts:
      type: none
      device: /var/panoptes
      o: bind

