version: '3.7'
services:
  develop-env:
    image: "${IMAGE:-panoptes-pocs}:${TAG:-develop}"
    init: true
    container_name: "${CONTAINER_NAME:-panoptes-pocs:develop}"
    privileged: true
    network_mode: host
    env_file: $PANDIR/env
    tty: true
    environment:
      - CLI_ARGS="${CLI_ARGS}"
    command:
      - "${POCS}/scripts/testing/run-tests.sh"
    volumes:
      - pandir:/var/panoptes
      - /var/panoptes/logs:/var/panoptes/logs
      - /var/panoptes/POCS:/var/panoptes/POCS
volumes:
  pandir:
    driver: local
    driver_opts:
      type: none
      device: /var/panoptes
      o: bind
