version: '3.7'
services:
  aag-weather-reader:
    image: gcr.io/panoptes-exp/aag-weather:latest
    init: true
    container_name: aag-weather-reader
    privileged: true
    network_mode: host
    restart: on-failure
    volumes:
      - pandir:/var/panoptes
    command:
      - "python"
      - "/app/scripts/read-aag.py"
      - "--config-file"
      - "/var/panoptes/conf_files/pocs_local.yaml"
      - "--db-file"
      - "/var/panoptes/json_store/panoptes/weather.db"
      - "--store-result"
      - "--verbose"
  aag-weather-server:
    image: gcr.io/panoptes-exp/aag-weather:latest
    init: true
    container_name: aag-weather-server
    privileged: true
    network_mode: host
    environment:
      - DB_NAME=/var/panoptes/json_store/panoptes/weather.db
    command: ["flask", "run"]
    restart: on-failure
    volumes:
      - pandir:/var/panoptes
volumes:
    pandir:
      driver: local
      driver_opts:
        type: none
        device: /var/panoptes
        o: bind

