version: '3.2'
services:
  peas-shell:
    image: gcr.io/panoptes-survey/pocs
    container_name: peas-shell
    privileged: true
    network_mode: host
    env_file: ${PANDIR}/env_file
    depends_on:
      - "messaging-hub"  
    volumes:
      - pandir:/var/panoptes
    command: /usr/bin/byobu new-session -s "POCS-Session" "/opt/conda/envs/panoptes-env/bin/python ${POCS}/scripts/peas-shell.py"
  pocs-shell:
    image: gcr.io/panoptes-survey/pocs
    container_name: pocs-shell
    privileged: true
    network_mode: host
    env_file: ${PANDIR}/env_file
    depends_on:
      - "peas-shell"  
    volumes:
      - pandir:/var/panoptes
        # command: /usr/bin/byobu new-session -s "POCS-Session" "/opt/conda/envs/panoptes-env/bin/python ${POCS}/scripts/pocs-shell.py"
    command: tail -f /dev/null
volumes:
    pandir:
      driver: local
      driver_opts:
        type: none
        device: /var/panoptes
        o: bind

